// Code generated by "stringer -type DatastructureType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Stack-1]
	_ = x[Heap-2]
}

const _DatastructureType_name = "UnknownStackHeap"

var _DatastructureType_index = [...]uint8{0, 7, 12, 16}

func (i DatastructureType) String() string {
	if i < 0 || i >= DatastructureType(len(_DatastructureType_index)-1) {
		return "DatastructureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DatastructureType_name[_DatastructureType_index[i]:_DatastructureType_index[i+1]]
}
