// Code generated by "stringer -type LogMode"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Noisy-0]
	_ = x[Silent-1]
}

const _LogMode_name = "NoisySilent"

var _LogMode_index = [...]uint8{0, 5, 11}

func (i LogMode) String() string {
	if i < 0 || i >= LogMode(len(_LogMode_index)-1) {
		return "LogMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogMode_name[_LogMode_index[i]:_LogMode_index[i+1]]
}
