// Code generated by "stringer -type datastructureType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[stack-1]
	_ = x[heap-2]
}

const _datastructureType_name = "unknownstackheap"

var _datastructureType_index = [...]uint8{0, 7, 12, 16}

func (i datastructureType) String() string {
	if i < 0 || i >= datastructureType(len(_datastructureType_index)-1) {
		return "datastructureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _datastructureType_name[_datastructureType_index[i]:_datastructureType_index[i+1]]
}
